# Generated by Django 4.2.6 on 2023-12-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexmeter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencies',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emergencies',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='emergencies',
            name='emergency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencies',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
