# Generated by Django 5.0 on 2023-12-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexmeter', '0002_emergencies_lat_emergencies_lon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencies',
            name='index',
        ),
        migrations.AddField(
            model_name='emergencies',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
