# Generated by Django 5.0 on 2023-12-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexmeter', '0003_remove_emergencies_index_emergencies_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencies',
            name='type',
        ),
    ]
