# Generated by Django 5.0 on 2023-12-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexmeter', '0004_remove_emergencies_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='indexes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexmeter.emergencies')),
            ],
        ),
    ]
