# Generated by Django 5.0 on 2023-12-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexmeter', '0005_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencies',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
