# Generated by Django 4.2.6 on 2023-11-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('y_coordinate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
