# Generated by Django 5.0 on 2023-12-10 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResponseApp', '0002_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireResources',
            fields=[
                ('fire', models.IntegerField(default=34)),
                ('rfid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalResourses',
            fields=[
                ('medical', models.IntegerField(default=34)),
                ('rfid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceResources',
            fields=[
                ('police', models.IntegerField(default=34)),
                ('rfid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
    ]
