# Generated by Django 5.0 on 2023-12-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResponseApp', '0003_fireresources_medicalresourses_policeresources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fireresources',
            name='location_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicalresourses',
            name='location_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='policeresources',
            name='location_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
