# Generated by Django 5.0 on 2023-12-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResponseApp', '0005_alter_coordinates_x_coordinate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='x_coordinate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='y_coordinate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
